# Generated by Django 5.0.6 on 2025-07-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='guidance_scale',
            field=models.FloatField(blank=True, default=7.5, help_text='Classifier-free guidance scale', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='num_inference_steps',
            field=models.IntegerField(blank=True, default=30, help_text='Number of denoising steps for generation', null=True),
        ),
    ]
