import uuid
from django.db import models
from django.utils import timezone


class KlingVideoJob(models.Model):
    """
    Model for storing Kling video generation job information
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    prompt = models.TextField(help_text="Text prompt for video generation")
    negative_prompt = models.TextField(blank=True, null=True, help_text="Things you do not want to see in the video")
    aspect_ratio = models.CharField(max_length=10, default="16:9", help_text="Aspect ratio of the video")
    start_image = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the first frame image")
    end_image = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the last frame image")
    reference_images = models.JSONField(default=list, blank=True, help_text="List of reference image URLs")
    cfg_scale = models.FloatField(default=0.5, help_text="Flexibility in video generation")
    duration = models.IntegerField(default=5, help_text="Duration of the video in seconds")
    
    # Output fields
    output_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the generated video")
    video_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to locally stored video")
    replicate_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the Replicate prediction")
    
    # Status fields
    status = models.CharField(
        max_length=20,
        default='starting',
        choices=(
            ('starting', 'Starting'),
            ('processing', 'Processing'),
            ('succeeded', 'Succeeded'),
            ('failed', 'Failed'),
            ('canceled', 'Canceled'),
        ),
        help_text="Current status of the job"
    )
    error_message = models.TextField(blank=True, null=True, help_text="Error message if job failed")
    
    # Meta information
    created_at = models.DateTimeField(auto_now_add=True, help_text="When the job was created")
    updated_at = models.DateTimeField(auto_now=True, help_text="When the job was last updated")
    completed_at = models.DateTimeField(null=True, blank=True, help_text="When the job was completed")
    
    # For webhook callbacks
    webhook_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL for Replicate to send webhook updates")
    webhook_secret = models.CharField(max_length=255, blank=True, null=True, help_text="Secret for webhook validation")
    client_webhook_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to send client webhook updates")

    class Meta:
        verbose_name = "Kling Video Job"
        verbose_name_plural = "Kling Video Jobs"
        ordering = ['-created_at']

    def __str__(self):
        return f"KlingVideo {self.id} - {self.status}"


class KlingLipsyncJob(models.Model):
    """
    Model for storing Kling lip-sync job information
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # Input fields - text-based input
    text = models.TextField(blank=True, null=True, help_text="Text content for lip sync (if not using audio)")
    voice_id = models.CharField(max_length=100, blank=True, null=True, default="en_AOT", 
                                help_text="Voice ID for speech synthesis (if using text and not audio)")
    voice_speed = models.FloatField(default=1.0, blank=True, null=True, 
                                   help_text="Speech rate (only used if using text and not audio)")
    
    # Input fields - audio-based input
    audio_file = models.URLField(max_length=1000, blank=True, null=True, 
                                help_text="Audio file for lip sync. Must be .mp3, .wav, .m4a, or .aac and less than 5MB")
    
    # Input fields - video sources
    video_id = models.CharField(max_length=100, blank=True, null=True, 
                               help_text="ID of a video generated by Kling. Cannot be used with video_url")
    video_url = models.URLField(max_length=1000, blank=True, null=True, 
                               help_text="URL of a video for lip syncing. Cannot be used with video_id")
    
    # Legacy fields - kept for backward compatibility
    audio_url = models.URLField(max_length=1000, blank=True, null=True, help_text="Legacy: URL to the audio file for lip-sync")
    image_url = models.URLField(max_length=1000, blank=True, null=True, help_text="Legacy: URL to the image to animate with lip-sync")
    prompt = models.TextField(blank=True, null=True, help_text="Optional additional prompt for generation")
    negative_prompt = models.TextField(blank=True, null=True, help_text="Things you do not want to see in the video")
    
    # Output fields
    output_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the generated video")
    video_output_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to locally stored video")
    replicate_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the Replicate prediction")
    
    # Status fields
    status = models.CharField(
        max_length=20,
        default='starting',
        choices=(
            ('starting', 'Starting'),
            ('processing', 'Processing'),
            ('succeeded', 'Succeeded'),
            ('failed', 'Failed'),
            ('canceled', 'Canceled'),
        ),
        help_text="Current status of the job"
    )
    error_message = models.TextField(blank=True, null=True, help_text="Error message if job failed")
    
    # Meta information
    created_at = models.DateTimeField(auto_now_add=True, help_text="When the job was created")
    updated_at = models.DateTimeField(auto_now=True, help_text="When the job was last updated")
    completed_at = models.DateTimeField(null=True, blank=True, help_text="When the job was completed")
    
    # For webhook callbacks
    webhook_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL for Replicate to send webhook updates")
    webhook_secret = models.CharField(max_length=255, blank=True, null=True, help_text="Secret for webhook validation")
    client_webhook_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to send client webhook updates")

    class Meta:
        verbose_name = "Kling Lipsync Job"
        verbose_name_plural = "Kling Lipsync Jobs"
        ordering = ['-created_at']

    def __str__(self):
        return f"KlingLipsync {self.id} - {self.status}"


class GoogleVeo3VideoJob(models.Model):
    """
    Model for storing Google Veo 3 video generation job information
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # Input fields
    prompt = models.TextField(help_text="Text prompt for video generation")
    negative_prompt = models.TextField(blank=True, null=True, help_text="Description of what to discourage in the generated video")
    enhance_prompt = models.BooleanField(default=True, help_text="Use Gemini to enhance your prompts")
    seed = models.IntegerField(blank=True, null=True, help_text="Random seed. Omit for random generations")
    
    # Output fields
    output_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the generated video")
    video_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to locally stored video")
    replicate_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to the Replicate prediction")
    
    # Status fields
    status = models.CharField(
        max_length=20,
        default='starting',
        choices=(
            ('starting', 'Starting'),
            ('processing', 'Processing'),
            ('succeeded', 'Succeeded'),
            ('failed', 'Failed'),
            ('canceled', 'Canceled'),
        ),
        help_text="Current status of the job"
    )
    error_message = models.TextField(blank=True, null=True, help_text="Error message if job failed")
    
    # Meta information
    created_at = models.DateTimeField(auto_now_add=True, help_text="When the job was created")
    updated_at = models.DateTimeField(auto_now=True, help_text="When the job was last updated")
    completed_at = models.DateTimeField(null=True, blank=True, help_text="When the job was completed")
    
    # For webhook callbacks
    webhook_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL for Replicate to send webhook updates")
    webhook_secret = models.CharField(max_length=255, blank=True, null=True, help_text="Secret for webhook validation")
    client_webhook_url = models.URLField(max_length=1000, blank=True, null=True, help_text="URL to send client webhook updates")

    class Meta:
        verbose_name = "Google Veo 3 Video Job"
        verbose_name_plural = "Google Veo 3 Video Jobs"
        ordering = ['-created_at']

    def __str__(self):
        return f"GoogleVeo3Video {self.id} - {self.status}"
