from rest_framework import serializers
from video_generation.models import KlingVideoJob, KlingLipsyncJob, GoogleVeo3VideoJob


class KlingVideoGenerateSerializer(serializers.Serializer):
    """
    Serializer for generating videos with Kling
    """
    prompt = serializers.CharField(required=True, help_text="Text prompt for video generation")
    negative_prompt = serializers.CharField(required=False, allow_blank=True, help_text="Things you do not want to see in the video")
    aspect_ratio = serializers.CharField(required=False, default="16:9", help_text="Aspect ratio of the video")
    start_image = serializers.URLField(required=False, allow_null=True, help_text="First frame of the video")
    end_image = serializers.URLField(required=False, allow_null=True, help_text="Last frame of the video")
    reference_images = serializers.ListField(
        child=serializers.URLField(),
        required=False,
        default=list,
        help_text="Reference images to use in video generation (up to 4 images)"
    )
    cfg_scale = serializers.FloatField(required=False, default=0.5, help_text="Flexibility in video generation")
    duration = serializers.IntegerField(required=False, default=5, help_text="Duration of the video in seconds (5 or 10)")
    client_webhook_url = serializers.URLField(required=False, allow_null=True, help_text="URL to send webhook updates to")
    
    def validate_duration(self, value):
        """Validate that duration is either 5 or 10 seconds"""
        if value not in [5, 10]:
            raise serializers.ValidationError("Duration must be either 5 or 10 seconds")
        return value
        
    def validate(self, data):
        """Validate that either start_image or end_image is provided"""
        start_image = data.get('start_image')
        end_image = data.get('end_image')
        
        if not start_image and not end_image:
            raise serializers.ValidationError("Either start_image or end_image is required")
            
        return data


class KlingVideoStatusSerializer(serializers.ModelSerializer):
    """
    Serializer for the status of a Kling video generation job
    """
    class Meta:
        model = KlingVideoJob
        fields = [
            'id', 'status', 'created_at', 'completed_at', 'error_message',
            'prompt', 'output_url', 'video_url', 'replicate_url'
        ]


class KlingLipsyncGenerateSerializer(serializers.Serializer):
    """
    Serializer for generating lip-sync videos with Kling
    """
    # Text-based input fields
    text = serializers.CharField(required=False, allow_blank=True, 
                                help_text="Text content for lip sync (if not using audio)")
    voice_id = serializers.CharField(required=False, default="en_AOT", 
                                   help_text="Voice ID for speech synthesis (if using text and not audio)")
    voice_speed = serializers.FloatField(required=False, default=1.0, 
                                       help_text="Speech rate (only used if using text and not audio)")
    
    # Audio-based input fields
    audio_file = serializers.URLField(required=False, allow_null=True, 
                                    help_text="Audio file for lip sync. Must be .mp3, .wav, .m4a, or .aac and less than 5MB")
    
    # Video source fields
    video_id = serializers.CharField(required=False, allow_null=True, 
                                   help_text="ID of a video generated by Kling. Cannot be used with video_url")
    video_url = serializers.URLField(required=False, allow_null=True, 
                                   help_text="URL of a video for lip syncing. Cannot be used with video_id")
    
    # Legacy fields - kept for backward compatibility 
    audio_url = serializers.URLField(required=False, allow_null=True, 
                                   help_text="Legacy: URL to the audio file for lip-sync")
    image_url = serializers.URLField(required=False, allow_null=True, 
                                   help_text="Legacy: URL to the image to animate with lip-sync")
    
    # Additional fields
    prompt = serializers.CharField(required=False, allow_blank=True, 
                                 help_text="Optional additional prompt for generation")
    negative_prompt = serializers.CharField(required=False, allow_blank=True, 
                                          help_text="Things you do not want to see in the video")
    client_webhook_url = serializers.URLField(required=False, allow_null=True, 
                                            help_text="URL to send webhook updates to")
    
    def validate_voice_speed(self, value):
        """Validate that voice_speed is between 0.8 and 2"""
        if value < 0.8 or value > 2:
            raise serializers.ValidationError("voice_speed must be between 0.8 and 2")
        return value
        
    def validate(self, data):
        """Validate input combinations"""
        # Legacy mode validation
        audio_url = data.get('audio_url')
        image_url = data.get('image_url')
        
        # New schema mode validation
        text = data.get('text')
        audio_file = data.get('audio_file')
        video_id = data.get('video_id')
        video_url = data.get('video_url')
        
        # Check if we're using legacy mode
        if audio_url and image_url:
            # Legacy mode, no additional validation needed
            return data
            
        # Check that we have either text or audio_file
        if not text and not audio_file and not audio_url:
            raise serializers.ValidationError(
                "Either 'text' or 'audio_file' must be provided for lip syncing")
        
        # Check that we have either video_id or video_url
        if not video_id and not video_url and not image_url:
            raise serializers.ValidationError(
                "Either 'video_id' or 'video_url' must be provided for lip syncing")
                
        # Check that video_id and video_url are not both provided
        if video_id and video_url:
            raise serializers.ValidationError(
                "Cannot use both 'video_id' and 'video_url' together")
                
        return data


class KlingLipsyncStatusSerializer(serializers.ModelSerializer):
    """
    Serializer for the status of a Kling lip-sync job
    """
    class Meta:
        model = KlingLipsyncJob
        fields = [
            'id', 'status', 'created_at', 'completed_at', 'error_message',
            'text', 'voice_id', 'voice_speed', 'audio_file', 'video_id', 'video_url',
            'prompt', 'output_url', 'video_output_url', 'replicate_url'
        ]


class GoogleVeo3GenerateSerializer(serializers.Serializer):
    """
    Serializer for generating videos with Google Veo 3
    """
    prompt = serializers.CharField(required=True, help_text="Text prompt for video generation")
    negative_prompt = serializers.CharField(required=False, allow_blank=True, help_text="Description of what to discourage in the generated video")
    enhance_prompt = serializers.BooleanField(required=False, default=True, help_text="Use Gemini to enhance your prompts")
    seed = serializers.IntegerField(required=False, allow_null=True, help_text="Random seed. Omit for random generations")
    client_webhook_url = serializers.URLField(required=False, allow_null=True, help_text="URL to send webhook updates to")


class GoogleVeo3StatusSerializer(serializers.ModelSerializer):
    """
    Serializer for the status of a Google Veo 3 video generation job
    """
    class Meta:
        model = GoogleVeo3VideoJob
        fields = [
            'id', 'status', 'created_at', 'completed_at', 'error_message',
            'prompt', 'negative_prompt', 'enhance_prompt', 'seed',
            'output_url', 'video_url', 'replicate_url'
        ]
