# Generated by Django 5.0.6 on 2025-06-28 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleVeo3VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='Text prompt for video generation')),
                ('negative_prompt', models.TextField(blank=True, help_text='Description of what to discourage in the generated video', null=True)),
                ('enhance_prompt', models.BooleanField(default=True, help_text='Use Gemini to enhance your prompts')),
                ('seed', models.IntegerField(blank=True, help_text='Random seed. Omit for random generations', null=True)),
                ('output_url', models.URLField(blank=True, help_text='URL to the generated video', max_length=1000, null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to locally stored video', max_length=1000, null=True)),
                ('replicate_url', models.URLField(blank=True, help_text='URL to the Replicate prediction', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='starting', help_text='Current status of the job', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL for Replicate to send webhook updates', max_length=1000, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255, null=True)),
                ('client_webhook_url', models.URLField(blank=True, help_text='URL to send client webhook updates', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Google Veo 3 Video Job',
                'verbose_name_plural': 'Google Veo 3 Video Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KlingLipsyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, help_text='Text content for lip sync (if not using audio)', null=True)),
                ('voice_id', models.CharField(blank=True, default='en_AOT', help_text='Voice ID for speech synthesis (if using text and not audio)', max_length=100, null=True)),
                ('voice_speed', models.FloatField(blank=True, default=1.0, help_text='Speech rate (only used if using text and not audio)', null=True)),
                ('audio_file', models.URLField(blank=True, help_text='Audio file for lip sync. Must be .mp3, .wav, .m4a, or .aac and less than 5MB', max_length=1000, null=True)),
                ('video_id', models.CharField(blank=True, help_text='ID of a video generated by Kling. Cannot be used with video_url', max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL of a video for lip syncing. Cannot be used with video_id', max_length=1000, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='Legacy: URL to the audio file for lip-sync', max_length=1000, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Legacy: URL to the image to animate with lip-sync', max_length=1000, null=True)),
                ('prompt', models.TextField(blank=True, help_text='Optional additional prompt for generation', null=True)),
                ('negative_prompt', models.TextField(blank=True, help_text='Things you do not want to see in the video', null=True)),
                ('output_url', models.URLField(blank=True, help_text='URL to the generated video', max_length=1000, null=True)),
                ('video_output_url', models.URLField(blank=True, help_text='URL to locally stored video', max_length=1000, null=True)),
                ('replicate_url', models.URLField(blank=True, help_text='URL to the Replicate prediction', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='starting', help_text='Current status of the job', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL for Replicate to send webhook updates', max_length=1000, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255, null=True)),
                ('client_webhook_url', models.URLField(blank=True, help_text='URL to send client webhook updates', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Kling Lipsync Job',
                'verbose_name_plural': 'Kling Lipsync Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KlingVideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='Text prompt for video generation')),
                ('negative_prompt', models.TextField(blank=True, help_text='Things you do not want to see in the video', null=True)),
                ('aspect_ratio', models.CharField(default='16:9', help_text='Aspect ratio of the video', max_length=10)),
                ('start_image', models.URLField(blank=True, help_text='URL to the first frame image', max_length=1000, null=True)),
                ('end_image', models.URLField(blank=True, help_text='URL to the last frame image', max_length=1000, null=True)),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='List of reference image URLs')),
                ('cfg_scale', models.FloatField(default=0.5, help_text='Flexibility in video generation')),
                ('duration', models.IntegerField(default=5, help_text='Duration of the video in seconds')),
                ('output_url', models.URLField(blank=True, help_text='URL to the generated video', max_length=1000, null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to locally stored video', max_length=1000, null=True)),
                ('replicate_url', models.URLField(blank=True, help_text='URL to the Replicate prediction', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='starting', help_text='Current status of the job', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL for Replicate to send webhook updates', max_length=1000, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255, null=True)),
                ('client_webhook_url', models.URLField(blank=True, help_text='URL to send client webhook updates', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Kling Video Job',
                'verbose_name_plural': 'Kling Video Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
