# Generated by Django 5.0.6 on 2025-06-28 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinimaxSpeechJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Text to be spoken')),
                ('voice_id', models.CharField(default='Wise_Woman', help_text="Desired voice ID (e.g., 'Wise_Woman', 'Friendly_Person', etc.)", max_length=50)),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en', 'es', 'fr')", max_length=10)),
                ('speed', models.FloatField(default=1.0, help_text='Speech speed multiplier (0.5-2.0)')),
                ('pitch', models.IntegerField(default=0, help_text='Speech pitch (-12 to 12)')),
                ('volume', models.FloatField(default=1.0, help_text='Speech volume (0-10)')),
                ('bitrate', models.IntegerField(default=128000, help_text='Bitrate for the generated speech')),
                ('channel', models.CharField(default='mono', help_text='Number of audio channels', max_length=10)),
                ('emotion', models.CharField(default='auto', help_text='Speech emotion', max_length=20)),
                ('sample_rate', models.IntegerField(default=32000, help_text='Sample rate for the generated speech')),
                ('language_boost', models.CharField(default='English', help_text='Enhance recognition of specific languages and dialects', max_length=20)),
                ('english_normalization', models.BooleanField(default=False, help_text='Enable English text normalization for better number reading')),
                ('model_version', models.CharField(choices=[('hd', 'HD'), ('turbo', 'Turbo')], help_text='Which model version to use', max_length=20)),
                ('output_url', models.URLField(blank=True, help_text='URL to the generated audio', max_length=1000, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='URL to locally stored audio', max_length=1000, null=True)),
                ('replicate_url', models.URLField(blank=True, help_text='URL to the Replicate prediction', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='starting', help_text='Current status of the job', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL for Replicate to send webhook updates', max_length=1000, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255, null=True)),
                ('client_webhook_url', models.URLField(blank=True, help_text='URL to send client webhook updates', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Minimax Speech Job',
                'verbose_name_plural': 'Minimax Speech Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinimaxVoiceCloneJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voice_file', models.URLField(help_text='URL to the reference audio for voice cloning', max_length=1000)),
                ('model', models.CharField(default='speech-02-turbo', help_text='The text-to-speech model to train', max_length=50)),
                ('accuracy', models.FloatField(default=0.7, help_text='Text validation accuracy threshold (0-1)')),
                ('need_noise_reduction', models.BooleanField(default=False, help_text='Enable noise reduction')),
                ('need_volume_normalization', models.BooleanField(default=False, help_text='Enable volume normalization')),
                ('output_url', models.URLField(blank=True, help_text='URL to the generated audio', max_length=1000, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='URL to locally stored audio', max_length=1000, null=True)),
                ('replicate_url', models.URLField(blank=True, help_text='URL to the Replicate prediction', max_length=1000, null=True)),
                ('replicate_id', models.CharField(blank=True, help_text='Replicate prediction ID for tracking job status', max_length=100, null=True)),
                ('preview', models.URLField(blank=True, help_text='Preview URL from the model', max_length=1000, null=True)),
                ('voice_id', models.CharField(blank=True, help_text='The voice ID of the trained model', max_length=50, null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='starting', help_text='Current status of the job', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL for Replicate to send webhook updates', max_length=1000, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255, null=True)),
                ('client_webhook_url', models.URLField(blank=True, help_text='URL to send client webhook updates', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Minimax Voice Clone Job',
                'verbose_name_plural': 'Minimax Voice Clone Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
