# Generated by Django 5.0.6 on 2025-06-28 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('podcast_idea', models.TextField(help_text='Main idea or topic for the podcast')),
                ('document_content', models.TextField(blank=True, help_text='Optional document content for additional context', null=True)),
                ('speaker_count', models.IntegerField(choices=[(1, 'Monologue'), (2, 'Dialogue')], default=1, help_text='Number of speakers in the podcast')),
                ('speaker1_name', models.CharField(default='Speaker 1', help_text='Name of the first speaker', max_length=100)),
                ('speaker1_audio_sample', models.URLField(help_text='URL to the audio sample for speaker 1', max_length=1000)),
                ('speaker1_image', models.URLField(help_text='URL to the image for speaker 1', max_length=1000)),
                ('speaker1_video_url', models.URLField(blank=True, help_text='URL to a pre-recorded video for speaker 1', max_length=1000, null=True)),
                ('speaker1_voice_id', models.CharField(blank=True, help_text='Voice ID from Minimax for speaker 1', max_length=50, null=True)),
                ('speaker1_image_analysis', models.TextField(blank=True, help_text="Analysis of speaker 1's image by Gemini", null=True)),
                ('speaker1_webhook_secret', models.CharField(blank=True, help_text='Secret for speaker 1 webhook validation', max_length=255, null=True)),
                ('speaker2_name', models.CharField(blank=True, default='Speaker 2', help_text='Name of the second speaker', max_length=100, null=True)),
                ('speaker2_audio_sample', models.URLField(blank=True, help_text='URL to the audio sample for speaker 2', max_length=1000, null=True)),
                ('speaker2_image', models.URLField(blank=True, help_text='URL to the image for speaker 2', max_length=1000, null=True)),
                ('speaker2_video_url', models.URLField(blank=True, help_text='URL to a pre-recorded video for speaker 2', max_length=1000, null=True)),
                ('speaker2_voice_id', models.CharField(blank=True, help_text='Voice ID from Minimax for speaker 2', max_length=50, null=True)),
                ('speaker2_image_analysis', models.TextField(blank=True, help_text="Analysis of speaker 2's image by Gemini", null=True)),
                ('speaker2_webhook_secret', models.CharField(blank=True, help_text='Secret for speaker 2 webhook validation', max_length=255, null=True)),
                ('media_folder', models.CharField(blank=True, help_text='Timestamped project folder for storing all generated media', max_length=120, null=True)),
                ('script', models.JSONField(blank=True, help_text='Generated script with dialogue and emotions', null=True)),
                ('background_prompt', models.TextField(blank=True, help_text='Prompt for generating consistent background', null=True)),
                ('background_image_reference', models.URLField(blank=True, help_text='URL to client-supplied background image to use instead of generating one', max_length=1000, null=True)),
                ('final_video_url', models.URLField(blank=True, help_text='URL to the final podcast video', max_length=1000, null=True)),
                ('voice_clone_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of voice cloning process', max_length=20)),
                ('script_generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of script generation process', max_length=20)),
                ('image_analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of image analysis process', max_length=20)),
                ('audio_generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of audio generation process', max_length=20)),
                ('video_generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of video generation process', max_length=20)),
                ('lipsync_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of lipsync process', max_length=20)),
                ('video_combination_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of video combination process', max_length=20)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='starting', help_text='Current status of the job', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL for Replicate to send webhook updates', max_length=1000, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255, null=True)),
                ('client_webhook_url', models.URLField(blank=True, help_text='URL to send client webhook updates', max_length=1000, null=True)),
                ('user', models.ForeignKey(help_text='User who created this job', on_delete=django.db.models.deletion.CASCADE, related_name='podcast_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Podcast Generation Job',
                'verbose_name_plural': 'Podcast Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastDialogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_name', models.CharField(help_text='Name of the speaker', max_length=100)),
                ('speaker_voice_id', models.CharField(help_text='Voice ID to use for this dialogue', max_length=50)),
                ('speech_job_id', models.UUIDField(blank=True, editable=False, help_text='UUID of the MinimaxSpeechJob for this dialogue', null=True)),
                ('sequence_number', models.IntegerField(help_text='Order of this dialogue in the conversation')),
                ('dialogue_text', models.TextField(help_text='Text content of this dialogue segment')),
                ('emotion', models.CharField(default='auto', help_text='Emotion to apply to this dialogue', max_length=50)),
                ('audio_url', models.URLField(blank=True, help_text='URL to the generated audio for this dialogue', max_length=1000, null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to the generated video for this dialogue', max_length=1000, null=True)),
                ('lipsync_url', models.URLField(blank=True, help_text='URL to the lip-synced video for this dialogue', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('audio_processing', 'Audio Processing'), ('audio_completed', 'Audio Completed'), ('video_processing', 'Video Processing'), ('video_completed', 'Video Completed'), ('lipsync_processing', 'Lipsync Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the dialogue processing', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='podcast_generator.podcastgenerationjob')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
    ]
