# Generated by Django 5.0.6 on 2025-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastdialogue',
            name='audio_presigned_url',
            field=models.URLField(blank=True, help_text='Presigned version of audio_url', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcastdialogue',
            name='lipsync_presigned_url',
            field=models.URLField(blank=True, help_text='Presigned version of lipsync_url', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcastdialogue',
            name='video_presigned_url',
            field=models.URLField(blank=True, help_text='Presigned version of video_url', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='document_presigned_url',
            field=models.URLField(blank=True, help_text='Presigned version of document_source_url (auto-generated)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='document_source_url',
            field=models.URLField(blank=True, help_text='Remote PDF/doc URL to ingest into document_content', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='final_video_presigned_url',
            field=models.URLField(blank=True, help_text='Presigned version of final_video_url', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='skip_audio',
            field=models.BooleanField(default=False, help_text='Skip TTS/audio generation stage'),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='skip_image',
            field=models.BooleanField(default=False, help_text='Skip preliminary image/background processing stage'),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='skip_lipsync',
            field=models.BooleanField(default=False, help_text='Skip lipsync stage – implies skip_video is False'),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='skip_video',
            field=models.BooleanField(default=False, help_text='Skip silent speaker-video generation stage'),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='speaker1_video_presigned_url',
            field=models.URLField(blank=True, help_text='Presigned version of speaker1_video_url', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='podcastgenerationjob',
            name='speaker2_video_presigned_url',
            field=models.URLField(blank=True, help_text='Presigned version of speaker2_video_url', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='podcastdialogue',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Audio clip (public URL)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='podcastdialogue',
            name='lipsync_url',
            field=models.URLField(blank=True, help_text='Lip-synced video (public URL)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='podcastdialogue',
            name='video_url',
            field=models.URLField(blank=True, help_text='Silent video (public URL)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='podcastgenerationjob',
            name='final_video_url',
            field=models.URLField(blank=True, help_text='Final podcast video (public URL)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='podcastgenerationjob',
            name='speaker1_video_url',
            field=models.URLField(blank=True, help_text='URL to a pre-recorded video for speaker 1 (public)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='podcastgenerationjob',
            name='speaker2_video_url',
            field=models.URLField(blank=True, help_text='URL to a pre-recorded video for speaker 2 (public)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='podcastgenerationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('script_processing', 'Script Processing'), ('audio_pending', 'Audio Pending'), ('audio_processing', 'Audio Processing'), ('video_pending', 'Video Pending'), ('video_processing', 'Video Processing'), ('lipsync_pending', 'Lipsync Pending'), ('lipsync_processing', 'Lipsync Processing'), ('final_combination', 'Final Combination'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', help_text='Current status of the job', max_length=30),
        ),
    ]
