# Generated by Django 5.0.6 on 2025-07-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "podcast_generator",
            "0002_podcastdialogue_audio_presigned_url_and_more",
        ),
    ]

    # NOTE:
    # This migration was added to resolve a branch divergence error during
    # deployment where Django detected two leaf nodes (0002 and a previously
    # recorded 0004).  The original 0004 file was removed in an earlier commit,
    # but the name still exists in some deployment environments.  Re-creating
    # the file with the current, final definition of the ``status`` field
    # restores a linear migration history and allows automated migration steps
    # in Docker / K8s to proceed without the interactive "--merge" prompt.

    operations = [
        migrations.AlterField(
            model_name="podcastgenerationjob",
            name="status",
            field=models.CharField(
                max_length=30,
                default="pending",
                choices=[
                    ("pending", "Pending"),
                    ("script_processing", "Script Processing"),
                    ("audio_pending", "Audio Pending"),
                    ("audio_processing", "Audio Processing"),
                    ("video_pending", "Video Pending"),
                    ("video_processing", "Video Processing"),
                    ("lipsync_pending", "Lipsync Pending"),
                    ("lipsync_processing", "Lipsync Processing"),
                    ("final_combination", "Final Combination"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                help_text="Current status of the job",
            ),
        ),
    ]
