apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: podcast-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: registry.digitalocean.com/app-registry-colab/ai-image-gen:latest
        command: ["celery", "-A", "config.celery", "beat", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
