# Generated by Django 5.0.6 on 2025-06-28 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoraTrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='Name for the LoRA model', max_length=255)),
                ('replicate_training_id', models.CharField(blank=True, help_text='ID returned by Replicate for the training job', max_length=255, null=True, unique=True)),
                ('replicate_model_version', models.CharField(blank=True, help_text='Version ID of the trained model', max_length=255, null=True)),
                ('replicate_model_owner', models.CharField(default='your-replicate-username', max_length=255)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='starting', max_length=20)),
                ('webhook_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_events_filter_used', models.JSONField(blank=True, default=list, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('client_webhook_url', models.URLField(blank=True, help_text='Client webhook URL for direct callbacks', max_length=1024, null=True)),
                ('input_image_urls', models.JSONField(default=list, help_text='List of URLs for training images')),
                ('trigger_word', models.CharField(help_text='Trigger word to use with the trained model', max_length=255)),
                ('seed', models.IntegerField(blank=True, help_text='Random seed for training', null=True)),
                ('steps', models.IntegerField(default=1000, help_text='Number of training steps')),
                ('lora_rank', models.IntegerField(default=4, help_text='LoRA rank parameter')),
                ('resolution', models.IntegerField(default=512, help_text='Training resolution')),
                ('batch_size', models.IntegerField(default=1, help_text='Training batch size')),
                ('learning_rate', models.FloatField(default=0.0001, help_text='Learning rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LoRA Training Job',
                'verbose_name_plural': 'LoRA Training Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trigger_word', models.CharField(blank=True, max_length=255, null=True)),
                ('replicate_owner', models.CharField(default='your-replicate-username', max_length=255)),
                ('replicate_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('replicate_model_version', models.CharField(blank=True, max_length=255, null=True)),
                ('base_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('training_images_urls', models.JSONField(blank=True, default=list, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(default=1000)),
                ('lora_rank', models.IntegerField(default=4, help_text='LoRA rank parameter')),
                ('resolution', models.IntegerField(default=512, help_text='Training resolution')),
                ('batch_size', models.IntegerField(default=1, help_text='Training batch size')),
                ('learning_rate', models.FloatField(default=0.0001, help_text='Learning rate')),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trained Model',
                'verbose_name_plural': 'Trained Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_images', to='model_training.trainedmodel')),
            ],
            options={
                'verbose_name': 'Training Image',
                'verbose_name_plural': 'Training Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
